# Generated by Django 3.2.5 on 2021-09-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('epassword', models.IntegerField()),
                ('esalary', models.IntegerField()),
                ('eemail', models.EmailField(default='@gmail.com', max_length=254)),
                ('econtact', models.CharField(max_length=30)),
            ],
        ),
    ]
